# Generated by Django 2.1.7 on 2019-03-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(blank=True, max_length=3, null=True)),
                ('airport_name', models.CharField(blank=True, max_length=67, null=True)),
                ('carrier_code', models.CharField(blank=True, max_length=2, null=True)),
                ('carrier_name', models.CharField(blank=True, max_length=28, null=True)),
                ('statistics_ofdelays_carrier', models.IntegerField(blank=True, null=True)),
                ('statistics_ofdelays_lateaircraft', models.IntegerField(blank=True, null=True)),
                ('statistics_ofdelays_nationalaviationsystem', models.IntegerField(blank=True, null=True)),
                ('statistics_ofdelays_security', models.IntegerField(blank=True, null=True)),
                ('statistics_ofdelays_weather', models.IntegerField(blank=True, null=True)),
                ('statistics_flights_cancelled', models.IntegerField(blank=True, null=True)),
                ('statistics_flights_delayed', models.IntegerField(blank=True, null=True)),
                ('statistics_flights_diverted', models.IntegerField(blank=True, null=True)),
                ('statistics_flights_ontime', models.IntegerField(blank=True, null=True)),
                ('statistics_flights_total', models.IntegerField(blank=True, null=True)),
                ('statistics_minutesdelayed_carrier', models.IntegerField(blank=True, null=True)),
                ('statistics_minutesdelayed_lateaircraft', models.IntegerField(blank=True, null=True)),
                ('statistics_minutesdelayed_nationalaviationsystem', models.IntegerField(blank=True, null=True)),
                ('statistics_minutesdelayed_security', models.IntegerField(blank=True, null=True)),
                ('statistics_minutesdelayed_total', models.IntegerField(blank=True, null=True)),
                ('statistics_minutesdelayed_weather', models.IntegerField(blank=True, null=True)),
                ('time_label', models.CharField(blank=True, max_length=7, null=True)),
                ('time_month', models.IntegerField(blank=True, null=True)),
                ('time_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
